sudo: false

language: python

services:
  - docker

branches:
  only:
  - dev

before_install:
  - pip3 install --upgrade pip setuptools wheel
  - docker pull rigetti/qvm
  - docker pull rigetti/quilc
  - docker run -p -d=true 5000:5000 rigetti/qvm -S
  - docker run -p -d=true 6000:6000 rigetti/quilc -S

install:
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install coveralls
  - pip3 install -r requirements.txt
  - pip3 install -e .


script:
  - pytest src/nisqai --cov src/nisqai
