sudo: false
language: python
matrix:
  include:
  - os: linux
  python: "3.5"
  addons:
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['gcc-4.9', 'g++-4.9']
  env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.5
  - os: linux
    python: "3.6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.6

branches:
  only:
  - dev

before_install:
  - pip3 install --upgrade pip setuptools wheel

install:
  pip3 install pytest
  pip3 install pytest-cov
  pip3 install coveralls
  pip3 install -r requirements.txt
  pip3 install -e .

script: export OMP_NUM_THREADS=1 && pytest src/nisqai --cov src/nisqai
